services:
  jenkins:
    image: jenkins/jenkins:alpine-jdk21
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"    # Jenkins web UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true  # Enables setup wizard
    user: "0:0"  # Runs as root to avoid permission issues with volumes (optional)

volumes:
  jenkins_data:
    name: jenkins_data
  