services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: ldap.my-domain.com
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=My Domain Inc
      - LDAP_DOMAIN=my-domain.com
      - LDAP_ADMIN_PASSWORD=admin_password
      - LDAP_CONFIG_PASSWORD=config_password
      - LDAP_READONLY_USER=false
      - LDAP_RFC2307BIS_SCHEMA=false
      - LDAP_BACKEND=mdb
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_DH_PARAM_FILENAME=dhparam.pem
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_CIPHER_SUITE=SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
      - LDAP_TLS_VERIFY_CLIENT=demand
      - LDAP_REPLICATION=false
      - KEEP_EXISTING_CONFIG=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_SSL_HELPER_PREFIX=ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs
    networks:
      - ldap_network
    restart: unless-stopped
    command: --copy-service

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin.my-domain.com
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
    depends_on:
      - openldap
    networks:
      - ldap_network
    restart: unless-stopped

volumes:
  ldap_data:
    driver: local
  ldap_config:
    driver: local
  ldap_certs:
    driver: local

networks:
  ldap_network:
    driver: bridge
