name: kroki-api
services:
  kroki:
    image: yuzutech/kroki
    restart: unless-stopped
    depends_on:
      - mermaid
      - bpmn
      - excalidraw
      - diagramsnet
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    ports:
      - "8000:8000"
    # If you do need to explicitly mount /tmp, make sure to include the exec option
    tmpfs:
      - /tmp:exec
  mermaid:
    image: yuzutech/kroki-mermaid
    restart: unless-stopped
    expose:
      - "8002"
  bpmn:
    image: yuzutech/kroki-bpmn
    restart: unless-stopped
    expose:
      - "8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    restart: unless-stopped
    expose:
      - "8004"
  #yuzutech/kroki-diagramsnet (experimental)
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    restart: unless-stopped
    expose:
      - "8005"
