services:
  vpljail:
    image: jcrodriguezvpl/jail-alpine-full:latest
    container_name: vpl-jail
    ports:
      - "7000:80"
    environment:
      - VPL_JAIL_PORT=80
      - VPL_JAIL_URLPATH=/
      - VPL_JAIL_SECURE_PORT=0 # To disable HTTPS set VPL_JAIL_SECURE_PORT=0
    volumes:
      - vpl_data:/var/vpl_jail
    restart: always
    networks:
      - vpljail_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
volumes:
  vpl_data:
    driver: local
networks:
  vpljail_network:
    driver: bridge
